version: '3.8'

services:
  graphqlapi:
    build: .
    image: graphqlapi
    ports:
      - '4000:4000'
    depends_on:
      - db
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017

volumes:
  dbdata6:

networks:
  node-network:
    driver: bridge